### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by Zn4rK** [nikkiii/flysystem-acd#1]
I cannot find the package over at packagist, so when running:
 `composer require nikkiii/flysystem-acd`

I get thrown an `InvalidArgumentException`.

**Comment by nikkiii** [comment]
Sorry, I guess I never added it!

I'm making no guarantees as to the stability of this package, but it's on Packagist now untagged, so you may need to specify the stability/master branch.

**Comment by Zn4rK** [comment]
Thank you!

**Comment by Zn4rK** [comment]
Can you maybe add the packagist hooks to this repository or just push the update-button?

Right now [nikkiii/flysystem-acd dev-master](https://packagist.org/packages/nikkiii/flysystem-acd) is pointing to the wrong commit, which in turn requires alex-phillips dev-streams PR, which no longer exists since it's merged...

**Comment by nikkiii** [comment]
Sorry about that, activated and updated it.

**Comment by Zn4rK** [comment]
No worries! :) Thank you!
