### ISSUE TITLE
I didn't get it to work with the README example

### ISSUE THREAD

**Issue by OskarStark** [nikkiii/flysystem-acd#7]
this is my code:
```php
    /**
     * {@inheritdoc}
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $this->io = new SymfonyStyle($input, $output);

        $this->io->title('Authorize Amazon Cloud Drive');

        $cache = new SQLite('email', './cache');

        $drive = new CloudDrive('email', 'client_id', 'secret', $cache);

        $response = $drive->getAccount()->authorize();

        if (!$response['success']) {
            print_r($response); // Get the URL from here
        }

        // Input the resulting redirected url
        $url = readline();

        $response = $drive->getAccount()->authorize($url);

        // Initialize Node
        Node::init($drive->getAccount(), $cache);

        // Sync your local cache with the current state of your Cloud Drive.
        $drive->getAccount()->sync();

        $flysystem = new Filesystem(new AmazonCloudDrive($drive));
    }
```

this is the output:
![bildschirmfoto 2016-11-14 um 15 21 51](https://cloud.githubusercontent.com/assets/995707/20268149/2b0f9b6e-aa7e-11e6-9d3c-36969f6c3688.png)

Nothing happens...

**Comment by nikkiii** [comment]
You never filled in the client id/secret from Amazon, the best guide I can give you is one I wrote for another project which somewhat applies, stopping at "Fill in the fields in config", instead using the client_id and secret in the CloudDrive constructor.

https://github.com/nikkiii/backupd#requirements

**Comment by OskarStark** [comment]
Hi @nikkiii 

Ok, i created a developer account and now I have a Security Profile with client_id and secret.
In the link you provided, i should:

> Whitelist the security profile (https://developer.amazon.com/cd/sp/overview.html), and edit the authorized urls

But the URL is not working!

![bildschirmfoto 2016-11-15 um 08 40 33](https://cloud.githubusercontent.com/assets/995707/20297132/345b8e3a-ab0f-11e6-8b3b-4f68d6218adf.png)

Best Oskar
